export interface User {
  id: string;
  fullName: string;
  username: string;
  department: string;
  role: 'doctor' | 'nurse' | 'staff' | 'admin';
}

export interface ShiftSession {
  id: string;
  userName: string;
  startTime: Date;
  endTime?: Date;
  isActive: boolean;
  bedStatuses: BedStatus[];
  teamMembers: string[];
  endApprovals: string[];
  notes?: string;
}

export interface BedStatus {
  department: string;
  totalBeds: number;
  occupiedBeds: number;
  freeBeds: { male: number; female: number };
}

export interface Patient {
  id: string;
  name: string;
  age: number;
  birthYear: number;
  gender: 'male' | 'female';
  country: string;
  roomNumber: string;
  department: string;
  condition: string;
  symptoms: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'stable' | 'critical' | 'improving' | 'deteriorating';
  allergies: string;
  medications: string;
  ecg: string;
  labResults: string;
  pciData: string;
  notes: string;
  isNewPatient: boolean;
  admissionType: 'emergency' | 'scheduled' | 'transfer';
  riskFactors: {
    smoking: boolean;
    hypertension: boolean;
    diabetes: boolean;
    obesity: boolean;
    dyslipidemia: boolean;
  };
  pciAccess: {
    radial: boolean;
    femoral: boolean;
    periproceduralHeparin: boolean;
  };
  addedBy: string;
  addedAt: Date;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  patientId?: string;
  patientName?: string;
  dueTime?: Date;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  completed: boolean;
  completedBy?: string;
  completedAt?: Date;
  addedBy: string;
  addedAt: Date;
  autoGenerated: boolean;
}

export interface ActivityLog {
  id: string;
  type: 'patient_added' | 'patient_updated' | 'task_completed' | 'shift_started' | 'shift_ended' | 'shift_joined' | 'shift_left' | 'patient_discharged' | 'patient_deceased' | 'bed_updated';
  description: string;
  user: string;
  timestamp: Date;
  relatedId?: string;
}

export interface DischargedPatient {
  id: string;
  name: string;
  birthYear: number;
  diagnosis: string;
  department: string;
  roomNumber: string;
  notes: string;
  dischargeReportDone: boolean;
  dischargedBy: string;
  dischargedAt: Date;
}

export interface DeceasedPatient {
  id: string;
  name: string;
  birthYear: number;
  country: string;
  department: string;
  roomNumber: string;
  diagnosis: string;
  deathReportDone: boolean;
  recordedBy: string;
  recordedAt: Date;
}

export interface ShiftReport {
  id: string;
  shiftId: string;
  startTime: Date;
  endTime: Date;
  participants: string[];
  patientsCount: number;
  tasksCompleted: number;
  totalTasks: number;
  dischargesCount: number;
  deathsCount: number;
  autoStopped: boolean;
  createdAt: Date;
}

// Original 4 departments only
export const DEPARTMENTS = [
  'Njësi koronare',
  'GJIK',
  'Kardiologji I', 
  'Kardiologji II'
];

export const DEPARTMENT_SHORT_NAMES = {
  'Njësi koronare': 'NjK',
  'GJIK': 'GJIK',
  'Kardiologji I': 'KI',
  'Kardiologji II': 'KII'
} as const;

export const DEPARTMENT_BED_COUNTS = {
  'Njësi koronare': 17,
  'GJIK': 15,
  'Kardiologji I': 21,
  'Kardiologji II': 18
} as const;

// Kosovo cities only
export const COUNTRIES = [
    'Deçan',
    'Dragash',
    'Drenas',
    'F.Kosovë',
    'Ferizaj',
    'Gjakovë',
    'Gjilan',
    'Graçanic',
    'Hani Elezit',
    'Istog',
    'Junik',
    'Kaçanik',
    'Kamenicë',
    'Klinë',
    'Kllokot',
    'Lipjan',
    'Malishevë',
    'Mamushë',
    'Mitrovicë',
    'Novobërdë',
    'Obiliq',
    'Partesh',
    'Pejë',
    'Podujevë',
    'Prishtinë',
    'Prizren',
    'Rahovec',
    'Ranillug',
    'Shtërpce',
    'Shtime',
    'Skenderaj',
    'Therandë',
    'Viti',
    'Vushtrri',
    'Mitrovicë E Veriut',
    'Zubin Potok',
    'Zveçan',
    'Leposaviq'
];